name: Submit to extension marketplace
description: Submit your extension to be automatically validated and published on the marketplace.
title: "[Submission]: "
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating an extension and submitting it to our marketplace!
  - type: input
    attributes:
      label: Docker Hub repository name
      description: Provide the Docker Hub repository name for your extension.
      placeholder: docker/resource-usage-extension
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        :warning: We automatically validate the greatest [semver](https://semver.org/) tag available on Docker Hub. See [the documentation](https://docs.docker.com/desktop/extensions-sdk/extensions/DISTRIBUTION/#release-your-extension) for more details.
  - type: checkboxes
    attributes:
      label: Terms of services
      options:
        - label: I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Once you have filled the form and submitted this issue, we will run automated validation on the extension.

        :+1: If everything goes well, a new label `validation/succeeded` will be added and the @docker/extensions will authorise the publication of the extension to the marketplace.

        :confused: If there are issues, you will see details in comments on the issue and information about how to fix them and re-run validation.

        If needed, we will use the email address associated with your Docker Hub account for any communication related to your extension.
